### ISSUE TITLE
Can't see the templates menu in editor

### ISSUE THREAD

**Issue by danswano** [rcdesign-cemetery/vb-foreign_mod_fixes#12]
Can't see the templates menu in editor although all permissions are correct and created all kind of templates.

**Comment by puzrin** [comment]
Patches are applied via TMS. You should install it first. Or patch templates manually, as described in original mod.

**Comment by danswano** [comment]
Is there any working TMS for VB 4.1.2 ?

**Comment by puzrin** [comment]
TMS for 3.х seems to work with 4.1. Don't remember details. You'd better ask in TMS thread http://www.vbulletin.org/forum/showthread.php?t=152931&highlight=tms

**Comment by danswano** [comment]
Thanks for the replies, the provided version worked well for me and the menu appeared in editor after re-installing.
